第一次Pull requests不知道这里该写啥
NERvGear/bangumi pull request #1
Opened 2022-03-26 04:25 UTC by SeasonG-CN

## 第一次Pull requests不知道这里该写啥

**除了saturday.xml和special.xml校对了一遍,其他都校对了两遍**
**睡觉去了**

2022-03-26 07:48 UTC, GPBeta commented
4 月新番应该放在 2022/spring/ 目录里面

2022-03-26 19:37 UTC, SeasonG-CN commented
> 4 月新番应该放在 2022/spring/ 目录里面

**整好啦**

2022-03-27 09:35 UTC, GPBeta commented
最好再挑几部火的把 rating 设为 10000 高亮显示

2022-03-27 10:32 UTC, SeasonG-CN commented
> 最好再挑几部火的把 rating 设为 10000 高亮显示

**改好啦**

2022-03-30 13:41 UTC, GPBeta requested changes
1 处需要修改

2022-03-30 13:41 UTC, GPBeta commented on 2022/spring/special.xml
> +			<en_GB>TIGER & BUNNY 2</en_GB>
应使用 `&amp` 替代 `&`

2022-03-31 01:14 UTC, SeasonG-CN commented on 2022/spring/special.xml
> +			<en_GB>TIGER & BUNNY 2</en_GB>
> 应使用 `&amp;` 替代 `&`

**好啦**

2022-03-31 07:15 UTC, merged